name: Server Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Create test data directory
      run: |
        mkdir -p ../tests/data
        cat > ../tests/data/test_backlog.json << 'EOL'
        {
          "tasks": [
            {
              "id": "T0001",
              "title": "ウェブサイトリニューアル",
              "type": "project",
              "status": "Open",
              "description": "企業ウェブサイトのデザインとコンテンツを刷新するプロジェクト",
              "assignable_to": [
                "human",
                "ai"
              ]
            },
            {
              "id": "T0002",
              "title": "ウェブサイトの分析レポート作成",
              "type": "task",
              "status": "Open",
              "description": "現行ウェブサイトの問題点と改善点を文書化する",
              "assignable_to": [
                "human",
                "ai"
              ]
            },
            {
              "id": "T0003",
              "title": "コンテンツ移行",
              "type": "task",
              "status": "Open",
              "description": "既存コンテンツを新サイトに移行する",
              "assignable_to": [
                "human",
                "ai"
              ],
              "dependencies": {
                "must": [
                  {
                    "task_id": "TASK-002",
                    "reason": "新デザインが確定してから移行作業を開始する"
                  }
                ],
                "nice_to_have": [
                  {
                    "task_id": "TASK-003",
                    "reason": "分析レポートを参考にしてコンテンツを改善できる"
                  }
                ]
              }
            },
            {
              "id": "T0004",
              "title": "SEO最適化",
              "type": "task",
              "status": "Open",
              "description": "新サイトのSEO対策を実施する。メタタグの最適化、構造化データの実装、パフォーマンス改善などを含む。",
              "assignable_to": [
                "human",
                "ai"
              ],
              "labels": [
                "technical",
                "high-priority"
              ],
              "dependencies": {
                "must": [
                  {
                    "task_id": "TASK-004",
                    "reason": "コンテンツ移行後にSEO最適化を行う"
                  }
                ]
              }
            }
          ]
        }
        EOL

    - name: Run tests
      run: npm test
      env:
        USE_TEST_DATA: 'true'

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: server/playwright-report/
        retention-days: 30
